version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.11.17-management-alpine # For now, more recent versions do not work in Mac M1
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: timescale/timescaledb:2.11.0-pg14
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: sensor_repository_repo
